[package]
name = "aghast"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["rt", "net"] }
tokio-util = { version = "0.7", features = ["rt"] }

twilight-http = { version = "0.16.0-rc.1", default-features = false, features = ["rustls-webpki-roots", "hickory"] }
twilight-interactions = "0.16.0-rc.1"
twilight-model = "0.16.0-rc.1"

valk-utils = "0.1"
thiserror = "2"
vss = "0.1"
axum = { version = "0.7.9", default-features = false, features = ["http2", "http1", "tokio", "json"] }
ed25519-dalek = "2.1.1"
serde_json = "1.0.133"
hex = "0.4.3"
futures-util = { version = "0.3.31", default-features = false }

